using System.Drawing.Imaging;
using System.Media;
using System.Runtime.InteropServices;

namespace Nitemare3DDataEditor;

public sealed class MainForm : Form
{
    private DatArchive? uif, snd; private FliAnimation? fli;
    private readonly TabControl tabs = new(); private readonly ListView uiList = new(), sndList = new(), fliList = new();
    private readonly PictureBox preview = new(), fliPreview = new(); private readonly Label status = new();

    public MainForm()
    {
        Text = "Nitemare 3D DAT / FLI Editor"; Width = 1200; Height = 760; MinimumSize = new Size(900, 560);
        var menu = new MenuStrip(); var file = new ToolStripMenuItem("Súbor");
        file.DropDownItems.Add("Otvoriť UIF.DAT", null, (_, _) => OpenDat(true)); file.DropDownItems.Add("Otvoriť SND.DAT", null, (_, _) => OpenDat(false)); file.DropDownItems.Add("Otvoriť ENDING.FLI", null, (_, _) => OpenFli());
        file.DropDownItems.Add("Uložiť UIF.DAT ako…", null, (_, _) => SaveDat(true)); file.DropDownItems.Add("Uložiť SND.DAT ako…", null, (_, _) => SaveDat(false)); file.DropDownItems.Add("Uložiť ENDING.FLI ako…", null, (_, _) => SaveFli());
        file.DropDownItems.Add("Exportovať vybranú položku/snímok", null, (_, _) => ExportSelected()); file.DropDownItems.Add("Importovať do vybranej položky/snímku", null, (_, _) => ImportSelected()); file.DropDownItems.Add("Prehrať vybraný zvuk/MIDI", null, (_, _) => PlaySelected()); file.DropDownItems.Add(new ToolStripSeparator()); file.DropDownItems.Add("Koniec", null, (_, _) => Close()); menu.Items.Add(file); MainMenuStrip = menu; Controls.Add(menu);
        tabs.Dock = DockStyle.Fill; var uiPage = new TabPage("UIF.DAT – grafika"); var sndPage = new TabPage("SND.DAT – MIDI a zvuky"); var fliPage = new TabPage("ENDING.FLI – animácia");
        ConfigureList(uiList); ConfigureList(sndList); ConfigureFliList(); uiList.SelectedIndexChanged += (_, _) => ShowUi(); sndList.SelectedIndexChanged += (_, _) => UpdateStatus(); fliList.SelectedIndexChanged += (_, _) => ShowFli();
        preview.Dock = DockStyle.Fill; preview.SizeMode = PictureBoxSizeMode.Zoom; preview.BackColor = Color.Black; var split = new SplitContainer { Dock = DockStyle.Fill, SplitterDistance = 360 }; split.Panel1.Controls.Add(uiList); split.Panel2.Controls.Add(preview); uiPage.Controls.Add(split); sndPage.Controls.Add(sndList);
        fliPreview.Dock = DockStyle.Fill; fliPreview.SizeMode = PictureBoxSizeMode.Zoom; fliPreview.BackColor = Color.Black; var fliSplit = new SplitContainer { Dock = DockStyle.Fill, SplitterDistance = 260 }; fliSplit.Panel1.Controls.Add(fliList); fliSplit.Panel2.Controls.Add(fliPreview); fliPage.Controls.Add(fliSplit);
        tabs.TabPages.Add(uiPage); tabs.TabPages.Add(sndPage); tabs.TabPages.Add(fliPage); Controls.Add(tabs); status.Dock = DockStyle.Bottom; status.Height = 28; status.Text = "Otvorte UIF.DAT, SND.DAT alebo ENDING.FLI."; Controls.Add(status);
    }
    private static void ConfigureList(ListView list) { list.Dock = DockStyle.Fill; list.View = View.Details; list.FullRowSelect = true; list.GridLines = true; list.Columns.Add("Slot", 70); list.Columns.Add("Typ", 110); list.Columns.Add("Bajtov", 90); list.Columns.Add("Offset", 100); list.Columns.Add("SHA-1", 110); }
    private void ConfigureFliList() { fliList.Dock = DockStyle.Fill; fliList.View = View.Details; fliList.FullRowSelect = true; fliList.GridLines = true; fliList.Columns.Add("Snímok", 75); fliList.Columns.Add("Bajtov", 100); fliList.Columns.Add("Stav", 90); }
    private void OpenDat(bool isUi) { using var d = new OpenFileDialog { Filter = "DAT súbory|*.dat;*.DAT|Všetky súbory|*.*" }; if (d.ShowDialog() != DialogResult.OK) return; try { if (isUi) { uif = DatArchive.Load(d.FileName); FillDat(uiList, uif, true); tabs.SelectedIndex = 0; } else { snd = DatArchive.Load(d.FileName); FillDat(sndList, snd, false); tabs.SelectedIndex = 1; } } catch (Exception ex) { MessageBox.Show(ex.Message, "Neplatný DAT", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
    private static string SoundType(DatEntry e) => e.IsEmpty ? "EMPTY" : AudioCodec.IsMidi(e.Data) ? "MIDI" : AudioCodec.IsVoc(e.Data) ? "VOC" : e.Index == 0 ? "IBK/RAW" : e.Index >= 34 ? "PCM 8-bit" : "RAW";
    private static void FillDat(ListView list, DatArchive archive, bool image) { list.Items.Clear(); foreach (var e in archive.Entries) { string type = image ? (e.IsEmpty ? "EMPTY" : PcxCodec.IsPcx(e.Data) ? "PCX 320×200" : "RAW") : SoundType(e); var item = new ListViewItem(e.Index.ToString()); item.SubItems.Add(type); item.SubItems.Add(e.Data.Length.ToString()); item.SubItems.Add(e.OriginalOffset.ToString()); item.SubItems.Add(e.Sha1); list.Items.Add(item); } }
    private void OpenFli() { using var d = new OpenFileDialog { Filter = "FLI animácia|*.fli;*.flc|Všetky súbory|*.*" }; if (d.ShowDialog() != DialogResult.OK) return; try { fli = FliAnimation.Load(d.FileName); fliList.Items.Clear(); foreach (var frame in fli.Frames) { var i = new ListViewItem(frame.Index.ToString()); i.SubItems.Add(frame.Raw.Length.ToString()); i.SubItems.Add("Pôvodný"); fliList.Items.Add(i); } tabs.SelectedIndex = 2; if (fliList.Items.Count > 0) fliList.Items[0].Selected = true; status.Text = $"ENDING.FLI: {fli.Frames.Count} snímkov, 320×200, {fli.Speed}/70 s"; } catch (Exception ex) { MessageBox.Show(ex.Message, "Neplatný FLI", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
    private void ShowUi() { if (uiList.SelectedIndices.Count == 0 || uif is null) return; try { using var bmp = PcxCodec.Decode(uif.Entries[uiList.SelectedIndices[0]].Data); preview.Image?.Dispose(); preview.Image = new Bitmap(bmp); status.Text = $"UIF slot {uiList.SelectedIndices[0]} – 320×200 PCX"; } catch { preview.Image?.Dispose(); preview.Image = null; UpdateStatus(); } }
    private void ShowFli() { if (fli is null || fliList.SelectedIndices.Count == 0) return; try { using var b = FliAnimation.ToBitmap(fli.Frames[fliList.SelectedIndices[0]]); fliPreview.Image?.Dispose(); fliPreview.Image = new Bitmap(b); var frame = fli.Frames[fliList.SelectedIndices[0]]; status.Text = $"ENDING.FLI snímok {frame.Index}/{fli.Frames.Count - 1} – {(frame.Modified ? "zmenený" : "pôvodný")}"; } catch (Exception ex) { status.Text = ex.Message; } }
    private void UpdateStatus() { if (tabs.SelectedIndex == 1 && sndList.SelectedIndices.Count > 0 && snd is not null) { var e = snd.Entries[sndList.SelectedIndices[0]]; status.Text = $"SND slot {e.Index} – {e.Data.Length} bajtov – {SoundType(e)}"; } }
    private DatEntry? SelectedDat(out bool isUi) { isUi = tabs.SelectedIndex == 0; var a = isUi ? uif : snd; var l = isUi ? uiList : sndList; if (a is null || l.SelectedIndices.Count == 0) return null; return a.Entries[l.SelectedIndices[0]]; }
    private void ExportSelected() { if (tabs.SelectedIndex == 2) { ExportFliFrame(); return; } var e = SelectedDat(out bool isUi); if (e is null) { MessageBox.Show("Najprv vyberte položku."); return; } string sndFilter = AudioCodec.IsMidi(e.Data) ? "MIDI|*.mid|Binárne|*.bin" : AudioCodec.IsVoc(e.Data) ? "WAV (dekódovaný VOC)|*.wav|Creative VOC|*.voc|Binárne|*.bin" : e.Index >= 34 ? "WAV|*.wav|RAW PCM|*.raw|Binárne|*.bin" : "Binárne|*.bin"; using var d = new SaveFileDialog { FileName = $"slot_{e.Index}", Filter = isUi ? "PNG obrázok|*.png|PCX|*.pcx|Binárne|*.bin" : sndFilter }; if (d.ShowDialog() != DialogResult.OK) return; try { string ext = Path.GetExtension(d.FileName).ToLowerInvariant(); if (isUi && ext == ".png") using (var b = PcxCodec.Decode(e.Data)) b.Save(d.FileName, ImageFormat.Png); else if (!isUi && ext == ".wav") File.WriteAllBytes(d.FileName, AudioCodec.ToWave(e.Data)); else File.WriteAllBytes(d.FileName, e.Data); } catch (Exception ex) { MessageBox.Show(ex.Message, "Export", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
    private void ExportFliFrame() { if (fli is null || fliList.SelectedIndices.Count == 0) { MessageBox.Show("Najprv otvorte ENDING.FLI a vyberte snímok."); return; } using var d = new SaveFileDialog { FileName = $"ending_{fliList.SelectedIndices[0]:0000}.png", Filter = "PNG obrázok|*.png" }; if (d.ShowDialog() != DialogResult.OK) return; using var b = FliAnimation.ToBitmap(fli.Frames[fliList.SelectedIndices[0]]); b.Save(d.FileName, ImageFormat.Png); }
    private void ImportSelected() { if (tabs.SelectedIndex == 2) { ImportFliFrame(); return; } var e = SelectedDat(out bool isUi); if (e is null) { MessageBox.Show("Najprv vyberte položku."); return; } using var d = new OpenFileDialog { Filter = isUi ? "PNG alebo BMP|*.png;*.bmp;*.jpg|PCX|*.pcx" : "MIDI/WAV/VOC/RAW|*.mid;*.midi;*.wav;*.voc;*.raw|Všetky súbory|*.*" }; if (d.ShowDialog() != DialogResult.OK) return; try { string ext = Path.GetExtension(d.FileName).ToLowerInvariant(); byte[] data; if (isUi && ext != ".pcx") using (var source = new Bitmap(d.FileName)) using (var scaled = new Bitmap(PcxCodec.Width, PcxCodec.Height)) using (var g = Graphics.FromImage(scaled)) { g.DrawImage(source, 0, 0, PcxCodec.Width, PcxCodec.Height); data = PcxCodec.Encode(scaled, PcxCodec.IsPcx(e.Data) ? PcxCodec.ReadPalette(e.Data) : PcxCodec.DefaultPalette()); } else if (!isUi && ext == ".wav") data = AudioCodec.IsVoc(e.Data) ? AudioCodec.WaveToVoc(File.ReadAllBytes(d.FileName)) : AudioCodec.FromWave(File.ReadAllBytes(d.FileName)); else data = File.ReadAllBytes(d.FileName); var a = isUi ? uif! : snd!; a.Replace(e.Index, data); FillDat(isUi ? uiList : sndList, a, isUi); status.Text = "Zmena je v pamäti; použite Uložiť."; } catch (Exception ex) { MessageBox.Show(ex.Message, "Import", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
    private void ImportFliFrame() { if (fli is null || fliList.SelectedIndices.Count == 0) { MessageBox.Show("Najprv vyberte snímok ENDING.FLI."); return; } using var d = new OpenFileDialog { Filter = "PNG alebo BMP|*.png;*.bmp;*.jpg" }; if (d.ShowDialog() != DialogResult.OK) return; try { using var b = new Bitmap(d.FileName); int index = fliList.SelectedIndices[0]; fli.ReplaceFrame(index, b); fliList.Items[index].SubItems[2].Text = "Zmenený"; ShowFli(); } catch (Exception ex) { MessageBox.Show(ex.Message, "Import FLI", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
    private void SaveDat(bool isUi) { var a = isUi ? uif : snd; if (a is null) { MessageBox.Show("Tento archív ešte nie je otvorený."); return; } using var d = new SaveFileDialog { FileName = Path.GetFileName(a.SourcePath), Filter = "DAT súbor|*.dat" }; if (d.ShowDialog() != DialogResult.OK) return; try { a.Save(d.FileName); status.Text = $"Uložené: {d.FileName}"; } catch (Exception ex) { MessageBox.Show(ex.Message, "Uloženie", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
    private void SaveFli() { if (fli is null) { MessageBox.Show("ENDING.FLI ešte nie je otvorený."); return; } using var d = new SaveFileDialog { FileName = Path.GetFileName(fli.SourcePath), Filter = "FLI animácia|*.fli" }; if (d.ShowDialog() != DialogResult.OK) return; try { fli.Save(d.FileName); status.Text = $"FLI uložené: {d.FileName}"; } catch (Exception ex) { MessageBox.Show(ex.Message, "Uloženie FLI", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
    private void PlaySelected() { var e = SelectedDat(out bool isUi); if (e is null || isUi || e.Data.Length == 0) { MessageBox.Show("Vyberte zvuk alebo MIDI položku v SND.DAT."); return; } if (!AudioCodec.IsMidi(e.Data) && !AudioCodec.IsVoc(e.Data) && e.Index < 34) { MessageBox.Show("Vybraná položka nie je prehrateľný zvuk."); return; } string temp = Path.Combine(Path.GetTempPath(), $"n3d_{Guid.NewGuid():N}"); try { if (AudioCodec.IsMidi(e.Data)) { string midi = temp + ".mid"; File.WriteAllBytes(midi, e.Data); Mci("open \"" + midi.Replace("\"", "") + "\" type sequencer alias n3dmid"); Mci("play n3dmid"); } else { string wav = temp + ".wav"; File.WriteAllBytes(wav, AudioCodec.ToWave(e.Data)); using var player = new SoundPlayer(wav); player.PlaySync(); File.Delete(wav); } } catch (Exception ex) { MessageBox.Show(ex.Message, "Prehrávanie", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
    [DllImport("winmm.dll", CharSet = CharSet.Unicode)] private static extern int mciSendString(string command, System.Text.StringBuilder? returnValue, int returnLength, IntPtr callback);
    private static void Mci(string command) => mciSendString(command, null, 0, IntPtr.Zero);
}

